
.PHONY:clean

CC=gcc
CFLAGS=-I/usr/include/lua5.3/
LDFLAGS=-llua5.3

mylib.so:mylib.o
	gcc -shared $(LDFLAGS) $(LDFLAGS) mylib.o -o mylib.so

mylib.o:mylib.c mylib.h
	gcc $(CFLAGS) -c mylib.c -fpic

clean:
	rm -f mylib.o mylib.so
